identities_registry.go
specs/activity.spec

new: index hojo activity in background

---

doc/documentation.md
recipe.go
specs/recipe.spec

Works with https://github.com/aporeto-inc/clad/pull/1099

add succesfull message

---

doc/documentation.md
enforcer.go
specs/enforcer.spec

fix: add operational status unknown

---

auditreport.go
doc/documentation.md
specs/auditreport.spec

Fix the documentation of the messages.

Fix audit api documentation

---

doc/documentation.md
graphedge.go
specs/+graphedge.spec

Adds Node source/dest types for the edges.

Add types for edge source/dest types

---

doc/README.md

- Adjusts the notes to use junon styling as this is the preferred renderer
- Minor grammatical and stylistic adjustments

Minor changes to README

---

doc/documentation.md
enforcer.go
specs/enforcer.spec

--> Seems like there's a way to set trace level.

fix: add trace level to enforcer log level

---

doc/documentation.md
enforcer.go
specs/enforcer.spec

--> `logLevelDuration` field to switch log level back to default after the limit.

new: log level interval

---

enforcer.go

--> Not sure what happened, but I regen'd the enforcer spec to fix it.

fix: duplicate field

---

custom_validations.go

Change validation property so UI can highlight the correct field when getting an error.
Fixes https://github.com/aporeto-inc/aporeto/issues/1648

update validation property

---

doc/documentation.md
relationships_registry.go
specs/service.spec

Part of project https://github.com/orgs/aporeto-inc/projects/614

fixed: remove unused parameter

---

doc/documentation.md
packetreport.go
specs/packetreport.spec

Change attributes to make sure they are exposed.

Change packet report attributes

---

Makefile
doc/documentation.md
ldapprovider.go
specs/ldapprovider.spec

new: added includeKeys to LDAPProvider

---

doc/documentation.md
enforcerlog.go
relationships_registry.go
specs/enforcerlog.spec

address feedbacks

---

doc/documentation.md
pingreport.go
processingunitrefresh.go
specs/pingreport.spec
specs/processingunitrefresh.spec

--> Renamed pingRequests to pingIterations.
--> Port range support is removed.
--> Some cleanups on pingreports.

fix: simplifying l3 ping

---

doc/README.md

- Updates the name of the API
- ~Adjust heading levels to optimize integration with docsite~

Nomenclature edits

---

constants/constants.go

new: add constraint violation key

---

doc/documentation.md
processingunitrefresh.go
specs/processingunitrefresh.spec

Fixes https://github.com/aporeto-inc/aporeto-devs/issues/409
Setting the default ping iteration to 1.

fix: set default pingIterations to 1

---

custom_validations.go

> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/481

Fixed: Enclose tag with single quotes

---

doc/README.md

Corrects a minor typographical error

Remove extra "the" (release branch)

---

doc/README.md

Remove extra "the"

---

custom_validations.go
custom_validations_test.go
doc/documentation.md
externalnetwork.go
networkaccesspolicy.go
protocols/protocols.go
specs/_validation.mapping
specs/externalnetwork.spec
specs/networkaccesspolicy.spec

This PR adds the type/code notation for icmp.
> Ref https://github.com/aporeto-inc/aporeto-devs/issues/704

new: support for icmp type/code notation

---

custom_validations.go
custom_validations_test.go
specs/_validation.mapping

This is the 3.14 release PR for https://github.com/PaloAltoNetworks/gaia/pull/535

New: Support NOT operator for CIDR entries in external networks (3.14)

---

doc/documentation.md
externalnetwork.go
specs/externalnetwork.spec

It is about time to remove v1 external network support and enforce v2 syntax `servicePorts`.

Update: Remove v1 external network support

---

specs/import.spec
specs/importreference.spec

Missed these two examples when doing the removal of v1 external networks.

Update: Missed updating two examples

---

.spelling
cachedflowreport.go
doc/documentation.md
flowreport.go
specs/@flow.abs

@sibicramesh could you take care of the enforcer side?

new: add 'enforcerID' field to FlowReport + CachedFlowReport

---

.spelling
cnssearch.go
cnssuggestion.go
doc/documentation.md
pcsearchresult.go
processingunit.go
specs/+pcsearchresult.spec
specs/cnssearch.spec
specs/cnssuggestion.spec
specs/processingunit.spec
specs/root.spec

OK in code to use the lowercase but in regular text, should be capitalized (these are acronyms). In addition, we are sticking with `Microsegmentation` for this release.

Capitalize acronyms in text: RQL, UNIX

---

custom_validations.go
custom_validations_test.go
go.mod
go.sum
netutils/cidr.go
netutils/cidr_test.go

Added more logic to check for the multicast range in UDP networks.
Added more checks for included n/w's not be present in the excluded n/w.
Added path compressed trie to make the above checks.
Fixes: https://redlock.atlassian.net/browse/CNS-1226
Unit tests

UDP TargetNetworks validation.

---

netutils/cidr.go
netutils/cidr_test.go

Rever the included network validation in UDP networks.

Fix the included network validation.

---

doc/documentation.md
oidcprovider.go
samlprovider.go
specs/oidcprovider.spec
specs/samlprovider.spec

Add description field for IODC and SAML

Update: make IODC and SAML described

---

.spelling
cnssearch.go
doc/documentation.md
identities_registry.go
pcsearchresult.go
pctimerange.go
relationships_registry.go
specs/+pcsearchresult.spec
specs/+pctimerange.spec
specs/_type.mapping
specs/cnssearch.spec

Update gaia model for RQL

---

netutils/cidr.go
netutils/cidr_test.go

More fixes made to the multicast UDP range checks.

Fix issues related to multicast UDP subnet checks.

---

.spelling
connectionexceptionreport.go
counterreport.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
identities_registry.go
reportsquery.go
specs/_validation.mapping
specs/connectionexceptionreport.spec
specs/counterreport.spec
specs/reportsquery.spec

This PR cherry-picks https://github.com/PaloAltoNetworks/gaia/pull/619 into branch `release-5.0.0`

cherry-pick https://github.com/PaloAltoNetworks/gaia/pull/619 for release-5.0.0

---

.spelling
connectionexceptionreport.go
counterreport.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
identities_registry.go
reportsquery.go
specs/_validation.mapping
specs/connectionexceptionreport.spec
specs/counterreport.spec
specs/reportsquery.spec

cherry-pick https://github.com/PaloAltoNetworks/gaia/pull/619 for release-6.0.0

---

doc/documentation.md
specs/tenant.spec

We now support Prisma ID when retrieving or deleting a tenant. We should reflect this in the documentation.

Update: Refresh Tenant doc to reflect Prisma ID support

---

doc/documentation.md
relationships_registry.go
specs/cloudnode.spec

Enable delete operations on cloud nodes.

Enable delete on cloudnodes

---

doc/documentation.md
enforcer.go
specs/enforcer.spec

>Fixes
https://redlock.atlassian.net/browse/CNS-1502

new: detected host mode container property on enforcer (#623)

---

custom_validations.go
custom_validations_test.go

Fixes the protocol/port validation.

Fix the protocol/port validation

---

.spelling
doc/documentation.md
identities_registry.go
putrafficaction.go
relationships_registry.go
specs/putrafficaction.spec
specs/root.spec

In order to allow the user to change the default behavior in the namespace, we need an api proxy. Currently it is a read-only api. We should allow to change the default behavior of the current namespace.
> Fixes: https://redlock.atlassian.net/browse/CNS-2211

New: PU traffic action proxy API

---

.spelling
cloudnetworkquery.go
doc/documentation.md
specs/cloudnetworkquery.spec

Adds the effective action parameter in cloud query and replaces the previous unreachable parameters.

Add effective action to cloud network query

---

cloudnetworkquery.go
doc/documentation.md
specs/cloudnetworkquery.spec

Removes the unreachable options from the graph calculations. They were creating too many issues.

Remove the unreachable options. Too many issues

---

cloudendpointdata.go
doc/documentation.md
specs/+cloudendpointdata.spec

Adds public IP addresses to endpoints in order to evaluate NAT address translation.

Add public IP addresses to endpoints

---

cloudendpointdata.go
doc/documentation.md
specs/+cloudendpointdata.spec

Ports the public IP fixes to 6.5

Add public IP addresses to endpoints (#666)

---

cloudgraphnode.go
doc/documentation.md
specs/+cloudgraphnode.spec

Adding public policies field for the graph return to account for multiple paths.

Add public policies

---

.spelling
cloudinterfacedata.go
cloudnetworkquery.go
doc/documentation.md
specs/+cloudinterfacedata.spec
specs/cloudnetworkquery.spec

Add availability zone in the ingestion of interfaces so that we can properly process transit gateways.

Add availability zone to interfaces

---

protocols/protocols.go

Adds Protocol 99 support for private encryption

Add PrivateEncryption protocol 99

---

cloudnetworkquery.go
doc/documentation.md
specs/cloudnetworkquery.spec

Expose the RawRQL attribute so that Larl can communicate to Yeul.

Expose the RAWRql field

---

.spelling
cloudschedulednetworkquery.go
doc/documentation.md
specs/cloudschedulednetworkquery.spec

Cloud graph result using mongo gridFS

---

.spelling
cloudschedulednetworkquery.go
doc/documentation.md
specs/cloudschedulednetworkquery.spec

This reverts commit 81d23c08bc1fd11ec45d509b40e0de04afa4c8c2.

Revert "Cloud graph result using mongo gridFS (#711)"

---

.github/workflows/build-go.yaml
Makefile
custom_validations.go
custom_validations_test.go
netutils/cidr.go

The linting tool has dropped support for 1.15, so time for some adjustments...

Try to build on Go 1.17, and try to keep building on Go 1.15

---

doc/documentation.md
graphedge.go
graphedgeflowdetails.go
relationships_registry.go
specs/+cloudloadbalancerdata.spec
specs/+graphedgeflowdetails.spec
specs/_type.mapping
specs/cloudnetworkquery.spec
specs/graphedge.spec
specs/root.spec

For more information, please read the description in [this MR](https://git.scm.prismacloud.io/prismacloud/pcn/backend/-/merge_requests/1472)

feature/jenova: include proto/port in suggested policies

---

azureresource.go
identities_registry.go
relationships_registry.go
specs/azureresource.spec

The plan will be to unmarshal the ID field of PC's JSON object that describes the azure resource. We pluck fields from it, stick it to the model, then store the whole JSON blobs. This will make the resource searchable, indexable, and retrievable.

neocna/milestone: model for storing azure resources

---

cachedflowreport.go
doc/documentation.md
flowreport.go
specs/@flow.abs

This reverts commit 199bc8d7d6d44b83b368867d64b1e4c90fafb148.

Revert "add external network id to flow report (#767)"

---

cloudendpointdata.go
doc/documentation.md
specs/+cloudendpointdata.spec

fix: Azure Outbound Path

---

cloudnetworkconfigdata.go
cloudscalesetdata.go
doc/documentation.md
openapi3_autogen/cloudipconfiguration.json
openapi3_autogen/cloudnetworkconfigdata.json
openapi3_autogen/cloudscaleset.json
openapi3_autogen/cloudscalesetdata.json
specs/+cloudnetworkconfigdata.spec
specs/+cloudscalesetdata.spec

- new model for cloudscale set to make it more efficient for indexing

fix: efficient cloudscale set indexing

---

.spelling
doc/documentation.md
namespace.go
openapi3_autogen/namespace.json
openapi3_autogen/processingunit.json
processingunit.go
specs/namespace.spec
specs/processingunit.spec

https://redlock.atlassian.net/browse/CNS-4400

new: ecs pu and ns type

---

cloudloadbalancerdata.go
doc/documentation.md
openapi3_autogen/cloudloadbalancerdata.json
specs/+cloudloadbalancerdata.spec

Add Attached Entities to cloud LB object.

---

.github/workflows/build-go.yaml
.spelling
Makefile
cloudendpointdata.go
cloudloadbalancer.go
cloudloadbalancerroute.go
cloudpublicipaddress.go
dnslookupreport.go
doc/documentation.md
enforcerprofile.go
go.mod
go.sum
openapi3_autogen/cloudendpointdata.json
openapi3_autogen/cloudloadbalancer.json
openapi3_autogen/cloudservicetag.json
openapi3_autogen/dnslookupreport.json
openapi3_autogen/enforcerprofile.json
specs/+cloudendpointdata.spec
specs/cloudloadbalancer.spec
specs/cloudloadbalancerroute.spec
specs/cloudpublicipaddress.spec
specs/dnslookupreport.spec
specs/enforcerprofile.spec

At some point we stopped running spelling, which caused a lot of technical debt to pile up. We should now run it with our CI once again, enforcing this.

Update: Re-enable spelling and fix errors

---

cloudnetworkrulesetdata.go
doc/documentation.md
openapi3_autogen/cloudnetworkrulesetdata.json
specs/+cloudnetworkrulesetdata.spec

added EffectiveSecurityGroup type

---

doc/documentation.md
openapi3_autogen/service.json
service.go
specs/service.spec

backport the "preserve proxy header" option on Services to 5.3

add proxy protocol preserve header (#826)

---

azureresource.go
specs/azureresource.spec

Resolves [CNS-5910](https://redlock.atlassian.net/browse/CNS-5910) by adding the needed attributes to support Azure MySQL Flexible Server and Server (single instance).

neocna: add support for Azure Server and FlexibleServer (MySQL)

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Adds a new GCP resource kind `ComputeForwardingRule`
This is part of CNS phase 1b (internet to VM with load balancer).

[CNS-6346] gcpresourceattrs add ComputeForwardingRule

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Adds a new GCP resource kind ComputeBackendService
This is part of CNS phase 1b (internet to VM with load balancer).

[CNS-6347] gcpresourceattrs add ComputeBackendService

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Part of CNS-6350
Adds support for GCP instanceGroups.

[CNS-6350] neocna/gcpresourceattrs: add ComputeInstanceGroup

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Part of [CNS-6349]
Adds support for GCP targetInstances.

[CNS-6349] neocna/gcpresourceattrs: add ComputeTargetInstance

---

cloudendpoint.go
cloudloadbalancer.go
cloudloadbalancerroute.go
cloudmanagednetwork.go
cloudnetworkinterface.go
cloudnetworkruleset.go
cloudnode.go
cloudpublicipaddress.go
cloudroutetable.go
cloudscalegroup.go
cloudscaleset.go
cloudsubnet.go
cloudvpc.go
custom_validations.go
custom_validations_test.go
specs/@prismabase.abs
specs/_validation.mapping
specs/cloudnode.spec

Moved `ValidateNativeID` to cloudnode entity so we can have per type validations

scale group arn regex fix

---

cloudschedulednetworkquery.go
doc/documentation.md
openapi3_autogen/cloudschedulednetworkquery.json
specs/cloudschedulednetworkquery.spec

added result id and batch id to cnq

---

doc/documentation.md
k8sasset.go
k8sresource.go
openapi3_autogen/k8sasset.json
specs/@k8sresourceattrs.abs

To prepare for relationship mapping of UAI assets, we now want to pull down endpoint slices from clusters.

New: Add EndpointSlices kind for k8ssourceattrs

---

doc/documentation.md
openapi3_autogen/k8sasset.json
relationships_registry.go
specs/root.spec

k8s resources root spec

---

doc/documentation.md
k8sasset.go
k8sresource.go
openapi3_autogen/k8sasset.json
specs/@k8sresourceattrs.abs

In preparation for Phase 2, and to remove spam from the debug logs, we will add ingress as an object to download and store on CNA side.

New: Add ingress to supported k8s resources

---

cloudnetworkqueryfilter.go
doc/documentation.md
openapi3_autogen/cloudnetworkqueryfilter.json
specs/+cloudnetworkqueryfilter.spec

updated naming for K8s filters

---

cloudendpoint.go
cloudloadbalancer.go
cloudloadbalancerroute.go
cloudmanagednetwork.go
cloudnetworkinterface.go
cloudnetworkruleset.go
cloudnode.go
cloudpublicipaddress.go
cloudroutetable.go
cloudscalegroup.go
cloudscaleset.go
cloudsubnet.go
cloudvpc.go
doc/documentation.md
openapi3_autogen/cloudendpoint.json
openapi3_autogen/cloudloadbalancer.json
openapi3_autogen/cloudloadbalancerroute.json
openapi3_autogen/cloudmanagednetwork.json
openapi3_autogen/cloudnetworkinterface.json
openapi3_autogen/cloudnetworkruleset.json
openapi3_autogen/cloudnode.json
openapi3_autogen/cloudpublicipaddress.json
openapi3_autogen/cloudroutetable.json
openapi3_autogen/cloudscalegroup.json
openapi3_autogen/cloudscaleset.json
openapi3_autogen/cloudsubnet.json
openapi3_autogen/cloudvpc.json
specs/@prismabase.abs

added k8s namespace field to cloudnode

---

cloudnetworkqueryfilter.go
doc/documentation.md
openapi3_autogen/cloudnetworkqueryfilter.json
specs/+cloudnetworkqueryfilter.spec

[CNS-8150] add boolean to track whether assets in certain VPCs should be excluded

---

cloudnetworkqueryfilter.go
doc/documentation.md
openapi3_autogen/cloudnetworkqueryfilter.json
specs/+cloudnetworkqueryfilter.spec

[CNS-8198] Add a field to store object names in cloud network queries

---

cloudschedulednetworkquery.go
doc/documentation.md
openapi3_autogen/cloudgraph.json
openapi3_autogen/cloudschedulednetworkquery.json
relationships_registry.go
specs/cloudschedulednetworkquery.spec
specs/root.spec

[CNS-9508] Add neocna force indirect path param
