PaloAltoNetworks/gaia

doc/documentation.md
enforcer.go
specs/enforcer.spec

fix: add unknown operational status

---

endpoint.go
specs/+endpoint.spec

Prior 3.5, we were using `scopes` in httpresourcespec files.
After 3.5, we moved to `allowedScopes` and keep the backward compatibility.
Storing the `scopes` property in the database is showing wrong Audit Logs that might be confusing.
For now, we still want to expose the `scopes` that are computed based on `allowedScopes`.
However, storing this property is no longer necessary.
> Reference: https://github.com/aporeto-inc/aporeto/issues/1377

fix: do not store scopes in the database anymore

---

custom_validations.go
custom_validations_test.go
doc/documentation.md
hookpolicy.go
specs/_validation.mapping
specs/hookpolicy.spec

**Issue:** https://github.com/aporeto-inc/aporeto/issues/1274
**Context:** when creating a hook, we want to relax the requirement that mTLS must be configured.
This PR makes the destination endpoint TLS configuration optional and adds a custom validator on the model to validate the optional attributes of `clientCertificate` & `clientCertificateKey`. The validator ensures that **if either one of these attributes are provided, then BOTH must be provided** even though the attributes are individually optional. In the event that a validation error is encountered, an elemental error is thrown which provides the user-agent with context on which attributes were provided and missing.

Make mTLS optional when defining a hook

---

automation.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
specs/_validation.mapping
specs/automation.spec

> the never ending issue :D
Now with all the recent changes to Bahamut, a NATS pubsub client can choose their desired response mode for their publication and subsequently a subscriber has the ability to respond back accordingly based upon the publishers desired response mode! This is all a fancy way of saying that you can now achieve "request/reply" semantics using the APIs exposed by our Bahamut package. To take advantage of the request/reply pattern, this PR adds a new trigger type to automations known as `Webhook` (_great name, I know!_).
When triggered, the behavioural difference will be that the **HTTP call will block until the actions have executed** . There must be **one (_and only one_) action** defined if this trigger type is used because the Javascript object returned by that …

new: add new webhook trigger type to automations

---

doc/documentation.md
packetreport.go
specs/packetreport.spec

Makes the protocol non-mandatory for packet reports in 3.11

Protocol not required

---

doc/documentation.md
specs/statsinfo.spec
statsinfo.go

Adding `packets` to the apoctl command.

fix: apoctl stats info|query for packets

---

custom_validations.go
custom_validations_test.go

--> Go easy on the regex and allow upto 128 chars.
--> [project](https://github.com/orgs/aporeto-inc/projects/556)

fix: allow upto 128 characters for hostservice name

---

customer.go
doc/documentation.md
relationships_registry.go
specs/customer.spec
specs/root.spec

* Update: Extend customer model to have LastReportTime
* Fixed: Add associatedBillingID param to search on for accounts
* Fixed: Make associatedBillingID also filterable
* Fixed: Extend customer model to all vince to retrieve customers
* Update: Remove unnecessary stuff

Update: Extend customer model to have LastReportTime (#392)

---

doc/documentation.md
packetreport.go
specs/packetreport.spec

The namespace field and pu ID field can be empty. If this is the case, pick the namespace from the caller.
Fields were marked as not exposed and lost in the process.

Fix fields in packet reports

---

custom_validations.go
custom_validations_test.go

As identified by @t00f, when the user misconfigures the automation's actions, the validation error that is produced should reflect the attribute that was misconfigured. Currently, the data attribute indicates that the trigger was misconfigured when in fact it was the actions.
Also simplified error handling in the unit tests.

fix: update error attribute to 'actions' when auto actions are misconfigured

---

custom_validations.go
custom_validations_test.go
specs/_validation.mapping
specs/tokenscopepolicy.spec
tokenscopepolicy.go

closes aporeto-inc/aporeto#2584

fixed: add validation to ensure tokenScopePolicy's assignedScopes is not empty

---

custom_validations.go
custom_validations_test.go

This PR adds validation to support the NOT operator in the Target Networks.
> Reference: https://github.com/aporeto-inc/aporeto-devs/issues/29

new: Add support for Outbounds ACLs in Target Networks

---

custom_validations.go
custom_validations_test.go

Same PR as this morning, but this time for UDP Target Networks.
For some reasons, we didn't have any test on this property.

fix: add validation for UDP target networks

---

custom_validations.go
custom_validations_test.go

Not operator needs to be supported in excluded networks as well (See [comment](https://github.com/aporeto-inc/aporeto-devs/issues/10#issuecomment-610731675))
This PR does the same check for TCP and UDP target networks
> Related to https://github.com/aporeto-inc/gaia/pull/464

Support NOT operator in excluded networks

---

.gitignore
custom_validations.go
custom_validations_test.go
netutils/cidr.go
netutils/cidr_test.go

_This PR will be backported in 3.14 for Outbound ACLs_
Introducing a `netutils` package to validate CIDR.
Usually, we are using `net.ParseCIDR` to validate a string.
Recently, we added the not operator in front of CIDR and the following example is no longer valid:
```
!10.0.0.0/8
```
Any `!` notation should be a subset of a non prefix CIDR. The following is valid:
```
0.0.0.0/0 !10.0.0.0/8
```

fix: improve CIDR validation in enforcer profiles

---

custom_validations.go

We cannot check if the organizational metadata is part of the metadata tags after creation, so remove this check from ValidateMetadata. The check is still useful for creation only.
> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/104

Fixed: Remove org tag check from ValidateMetadata as it is validated on all actions

---

netutils/cidr.go
netutils/cidr_test.go

- Added validation on cases where cidr is not respecting the correct format and masks are not contained.
- Added check on network being both included and excluded
- Added support for IPv6
Fixes: aporeto-inc/aporeto-devs#113

added validation on cidr mask validation

---

doc/documentation.md
relationships_registry.go
specs/pingprobe.spec
specs/root.spec

Used for retrieving ping probes from a remote namespace using probe ID.

fix: enable filtering for pingprobes

---

custom_validations.go
custom_validations_test.go

Prior to this PR, we were using the hostname regex from github.com/go-playground/validator to validate FQDNs which is why a simple string like `asdasd` would match. Fortunately, they added an FQDN regex just 3 months back which also supported a trailing dot. Added that, simplified, and added a couple more unit tests to cover what found the issue and a path in the code that was missed.
> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/723

Update: Use FQDN validation from same source as original regex

---

custom_validations.go
custom_validations_test.go

This is just in case we need to revert the regex due to needing to support basic hostnames as well.

Revert "Update: Use FQDN validation from same source (#541)"

---

custom_validations.go
custom_validations_test.go

In the spirit of fixing https://github.com/aporeto-inc/aporeto-devs/issues/862 I decided to tackle all custom validation error messages and align them all with the same syntax. While I could have still missed a few spots, I think there is more consistent now. : )
> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/862

Update: Align error message syntax for custom_validations

---

.spelling
doc/documentation.md
namespace.go
specs/namespace.spec

Namespace types have been revised to the following:
- Tenant
- CloudAccount
- HostGroup
- KubernetesClusterGroup
- Kubernetes
The bottom three are new and `Group` is removed.
> Fixes: https://redlock.atlassian.net/browse/CNS-454

Update: Revised namespace types

---

.travis.yml

golang v1.15.x has been out for a while, so we may as well move travis over to supporting it and dropping 1.13.x.

Update: Bump travis to support two most recent minor language versions

---

doc/documentation.md
namespace.go
namespacepolicyinfo.go
specs/namespace.spec
specs/namespacepolicyinfo.spec

To align with the Unified Rules Engine and our revised distinction of incoming and outgoing actions on PU traffic, we want to split the EnforcerDefaultBehavior property on namespace into two.

New: Split and rename EnforcerDefaultBehavior into two directions

---

cachedflowreport.go
flowreport.go
specs/@flow.abs

The field `ai` was already used in the `CachedFlowReport` model. Using a new name instead.

fix: field name conflict CachedFlowReport

---

.spelling
doc/documentation.md
identities_registry.go
metricsquery.go
metricsqueryrange.go
relationships_registry.go
specs/metricsquery.spec
specs/metricsqueryrange.spec
specs/root.spec

This PR exposes the VM `/api/v1/query` endpoint so clients can make "[instant queries](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries)" and renames the APIs as follows:
1. `[GET|POST] /metricsquery` _(proxy API to vm's /api/v1/query endpoint)_
2. `[GET|POST] /metricsqueryrange` _(proxy API to vm's /api/v1/query_range endpoint)_

new: expose the VictoriaMetrics' '/api/v1/query' endpoint

---

doc/documentation.md
networkrule.go
specs/+networkrule.spec

CNS-1029 - Limit the ruleset name to 16 characters
@t00f @ericrpowers Can you please help with the review.

Restricting the name of the Ruleset object to be 16 characters.

---

doc/documentation.md
externalnetwork.go
specs/externalnetwork.spec

As we transition to v2 policy renderer, we will start to drop support for external networks. The first step is that we migrated all service ports from related external networks to network rule set policies, so this attribute is no longer applicable. To avoid bad user experience, we are now going to only allow creating external networks without service ports OR allow existing external networks to have their service ports unchanged or emptied on updates.

Update: Make service ports optional for external networks

---

cachedflowreport.go
doc/documentation.md
flowreport.go
specs/@flow.abs

Protocol 0 is valid so making it not required.
https://redlock.atlassian.net/browse/CNS-1361

Make protocol not required

---

.spelling
connectionexceptionreport.go
counterreport.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
identities_registry.go
reportsquery.go
specs/_validation.mapping
specs/connectionexceptionreport.spec
specs/counterreport.spec
specs/reportsquery.spec

https://redlock.atlassian.net/browse/CNS-1554
https://github.com/orgs/aporeto-inc/projects/1021
This CL does a few things:
- adds a `namespace` property to our `CounterReport` & `ConnectionExceptionReport` models in order to make them queryable by our [reportsqueries API](https://github.com/PaloAltoNetworks/gaia/blob/master/specs/reportsquery.spec).
- adds missing compound index to `ConnectionExceptionReport`
- adds `ReportsQuery` support for `ConnectionExceptionReport`
- If the new `namespace` field is present, use that. Otherwise, do what you did before.

CNS-1554: add 'namespace' property to CounterReport & ConnectionExceptionReport + misc.

---

Makefile

Uses the spell checker from our own repo to avoid rate limits from docker.

Add gcr repo to avoid rate limits

---

cloudinterfacedata.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
specs/+cloudinterfacedata.spec

Adds new type of interface (Unsupported) since AWS can send us anything there. We just mark it as unsupported.
Adds a set of validations so that source/destination IPs cannot be private IP addresses.

Unsupported interfaces and validation fixes

---

cloudgraphnode.go
doc/documentation.md
specs/+cloudgraphnode.spec
specs/_type.mapping

Adds the children IDs for every node in the graph output

Add children IDs to cloud graph output

---

cachedflowreport.go
doc/documentation.md
flowreport.go
specs/@flow.abs

https://redlock.atlassian.net/browse/CNS-2350
--- 
Our datapath model is doing mutual auth, which means during the process we validate the policy on both client and server side. Right now we report the policy ID at the endpoint where we decide to accept/drop the packet. The goal is to report the policy ID being validated at the remote end.
`remotePolicyID` - ID of the network policy that accepted the flow at the remote endpoint. Unfortunately, we cant add `remotePolicyNamespace` at the moment but having this partial info will atleast let us know that there are 2 policies being validated during our auth process.
Endpoint | Action | NetworkState | Fields 
-- | -- | -- | -- 
Server | Reject | Syn | N/A 
Client | Reject | SynAck | remotePolicyID == Destination PolicyID
Server | Accept | Ack | …

new: remote policy ID in flowreport

---

cloudnetworkquery.go
cloudnetworkqueryfilter.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
specs/+cloudnetworkqueryfilter.spec
specs/cloudnetworkquery.spec

Adds new options for cloud network query:
1. Excluded Networks that are enterprise networks that should not be taken into account in the search.
2. ServiceNames and resource type of Service to allow queries for cloud services (VPC endpoints)

Add excluded networks and services

---

cachedflowreport.go
flowreport.go
specs/@flow.abs

This fixes a conflict between `isLocalDestinationID` bson_name in `cachedflowreport.spec` and @flow.spec

fix: conflict in bson_name

---

custom_validations.go
custom_validations_test.go

Port 0 used to be an invalid port to set for service port workflows, like external networks and network rule set policies. We are now going to allow port 0 to be set.
> Fixes: https://redlock.atlassian.net/browse/CNS-2424

Update: Allow zero port for service port validation

---

portutils/portuils.go
portutils/portutils_test.go

This fixes the port validation to allow TCP ports of 0 in all validation checks (portutils used by services and NEP)

Fix port validation in all places

---

cloudnetworkquery.go
specs/cloudnetworkquery.spec

Excluded networks must be CIDRs.

Fix CIDR validation for excluded networks

---

custom_validations.go
custom_validations_test.go

This will allows runtime linking to ServiceCertificates

new/services: allow to set TLSCertificate without TLSCertificateKey

---

custom_validations.go
custom_validations_test.go

Add validations that mandates that a VPC must be provided for all the east/west graph calculations.

Add validations that only east/west graphs when VPC is provided

---

custom_validations.go
custom_validations_test.go
helpers_test.go
networkrulesetpolicy.go
networkrulesetpolicy_test.go
specs/networkrulesetpolicy.spec

This PR also make the first letter of error messages uppercase for consistency.
Reference JIRA tickets: [CNS-2829](https://redlock.atlassian.net/browse/CNS-2829?atlOrigin=eyJpIjoiNGQ1ZWNjYjU2MjFiNGM3ODllZjBmOTI5Mzg0OGMzOTgiLCJwIjoiaiJ9) and [CNS-2830](https://redlock.atlassian.net/browse/CNS-2830?atlOrigin=eyJpIjoiYjI5MGMwNGM1MmNkNDFkMmIwMDg2ZGQ1MGU3NzM3NTkiLCJwIjoiaiJ9)

Bugfix: prevent duplicate expressions in NetRuleSetPolicy's subject

---

apicheck.go
doc/documentation.md
specs/apicheck.spec

Validate `namespace` property to get a 422 instead of a 500 in case of bad input

fixed/apicheck: validate input namespace

---

doc/documentation.md
relationships_registry.go
specs/root.spec

Some namespaces are created with the protected state set to true. There are situations where a System Admin would want to update a namespace's tag prefixes and currently we do not allow proxy APIs to edit protected namespaces. To allow this use-case, we are introducing the parameter `force` on tagprefix API which, when set to true, will bypass protected state to update the tag prefixes.
> Fixes: https://redlock.atlassian.net/browse/CNS-3251

New: Add force parameter for tagprefix API

---

accessreport.go
doc/documentation.md
reportsquery.go
specs/accessreport.spec
specs/reportsquery.spec

This PR modifies the ReportQuery model in order to support reading out AccessReports via the /reportsQuery endpoint.  Note that new field `Namespace` is introduced to AccessReport because when jenova attempts to read out access reports, it makes a query to mongodb using the namespace filter... Without that field, the results will always be empty. For more information, see [this sister PR](https://git.scm.prismacloud.io/prismacloud/pcn/backend/-/merge_requests/1496)

ReportsQuery: add support for reading out AccessReports

---

doc/documentation.md
enforcerprofile.go
specs/enforcerprofile.spec

Adds flowReportInterval to enforcer profile, and defaults it to 30m.
We are moving flow reporting interval from the enforcer command line to the enforcer profile.
https://redlock.atlassian.net/browse/CNS-3595
Added enforcer unit test for updating flow report interval via enforcer profile.
Manual testing against AIO backend with gaia changes.

add flowReportInterval to enforcer profile

---

connectionexceptionreport.go
doc/documentation.md
specs/connectionexceptionreport.spec

This changes is for the Enforcer's TFO discovery feature.  We needed an additional enum value on the connectionexceptionreport.

Added TFOProbe

---

azureresource.go
specs/azureresource.spec

There is no reason to store the raw AzureResource's data as a `string`. This is because this field has no purpose other than passing its data to a json decoder/unmrashaler, which requires `[]byte`. In Go, `string` is immutable type. This means a statement like `[]byte(str)`, will trigger a copy of `str` since `[]byte` is mutable. To avoid this unnecessary allocation, we simply deal with the `[]byte` type.
This is the first instance in our models to have a stored field of type `[]byte`. I verified that it works correctly. Checking the stored field shows that raw bytes are stored as binary data and displayed as base64.
The following is an example of AzureResource stored via a mongo manipulator:
```
{ "_id" : ObjectId("623b7d95d62b9944c1e9ba2f"), "data" : …
```

neocna/improvement: change type of Data from string to []byte

---

cloudnetworkqueryfilter.go
custom_validations.go
custom_validations_test.go
doc/documentation.md
openapi3_autogen/cloudnetworkqueryfilter.json
specs/+cloudnetworkqueryfilter.spec

Add PaaS related attributes.
The reason we are creating new attributes instead of reusing the `servcieName` is that we need to have one to one mapping between the new `paas` RQL filter and the cloud query filter object. If we reuse `serviceName`, we cannot easily convert cloud query filter object back to `paas` RQL.

Update: PaaS support

---

doc/documentation.md
openapi3_autogen/service.json
service.go
specs/service.spec

add a `proxyProtocolPreserveHeader` field for Services
There should be an option to control whether enforcer strips the PROXY protocol header when forwarding traffic for a Service.
By default, it should strip the header.
https://redlock.atlassian.net/browse/CNS-5584

add proxy protocol preserve header

---

cloudschedulednetworkquery.go
doc/documentation.md
openapi3_autogen/cloudschedulednetworkquery.json
specs/_type.mapping
specs/cloudschedulednetworkquery.spec

Adding a new field for `successfulTimeStampMap` for every account
Vargid scheduler schedules a bunch of policies for evaluation to NATS server which gets picked by Yeul Worker. The Yeul Worker picks up a job from the NATS server and executes the query for evaluation. It returns the result to Vargid API to aggregate and raise the alerts.
When Vargid API receives the `cloudschedulednetworkquery` response back, it updates the object's `successfulExecutionTimeStamp` with the time that it receives the response. This information is crucial in identifying alerts which are not raised in this successful run (i.e. while alert aggregation, the current set of alerts in this policy run is updated with the latest time stamp and the old alerts are left with the timestamp of the policy run in which it …

fix: alert flip flops

---

doc/documentation.md
openapi3_autogen/processingunit.json
openapi3_autogen/renderedpolicy.json
relationships_registry.go
specs/processingunit.spec
specs/root.spec

As a step towards moving the policy rendering to enforcerd, we want to avoid sending all the entries of related external networks with rendered policies. Since enforcer has a backwards compatibility requirement (~9 month lookback), we will add a new optional boolean parameter on create or retrieve requests `stripNetworkEntries`. When set to true, the entries of all related external networks in a rendered policy will have their entries field stripped to lighten the load.

New: Add stripNetworkEntries optional parameter to rendered policy workflow

---

.github/workflows/build-go.yaml

golangci-lint introduced changes that support generics, which is now causing build issues on golang v1.17.x (meaning it no longer supports this version). Isolating golang v1.17.x to newest supported golangci-lint version.

Fixed: Lock golangci-lint on v1.17 due to generics

---

Makefile

With golangci-lint moving to v1.49.0, it enabled package comments which we do not do in practice. Also three linters have become deprecated as shown here:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
```
This PR adjusts the linter to be happy with v1.49.0.

Update: Support golangci-lint v1.49.0

---

.spelling
doc/documentation.md
openapi3_autogen/cloudgraph.json
relationships_registry.go
specs/root.spec

This PR introduces a new qry param that can be set to force yeul to ignore check for whether tenant is onboarded to use neocna.

yeul/cloudgraph/create: introduce qry param 'neocna'

---

.spelling
azureresource.go
cloudschedulednetworkquery.go
doc/documentation.md
openapi3_autogen/cloudschedulednetworkquery.json
specs/azureresource.spec
specs/cloudschedulednetworkquery.spec

This PR makes two changes:
1. Make `azureResource` timeable so we can later invoke the accountcleaner against that identity
2. Introduce a backwards-compatible flag called `neoCNA` to `CloudScheduledNetworkQuery` so we can test alerts from `vargid` with `neocna` in `yeul`.

neocna/alerts: integration with vargid

---

identities_registry.go
specs/azureresource.spec

If we don't get resourceID to load a resources, we will always get kind and, optionally, subscriptionIDs.

neocna/azureresource: build proper indexes

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

This field is needed so we can grep for resources based on their geo scopes, eg zonal, regional, or global.

neocna/gcp: new GeoScope property

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Part of CNS-6354
Adds support for GCP networkEndpointGroups.

[CNS-6354] neocna/gcpresourceattrs: add ComputeNetworkEndpointGroup

---

doc/documentation.md
gcpasset.go
gcpresource.go
openapi3_autogen/gcpasset.json
specs/@gcpresourceattrs.abs

Part of CNS-6352 and CNS-6353
Adds support for GCP targetTcpProxy and targetSslProxy resources.

 [CNS-6352][CNS-6353] neocna/gcpresourceattrs: add ComputeTargetSSLProxy and ComputeTargetTCPProxy 

---

custom_validations.go
custom_validations_test.go

removed regex check on nativeID field as many objects from different cloud providers allow special characters and space

removed regex validation on nativeID

---

doc/documentation.md
floodparam.go
floodrpc.go
openapi3_autogen/cloudgraph.json
relationships_registry.go
specs/+floodparam.spec
specs/_type.mapping
specs/floodrpc.spec
specs/root.spec

These changes are needed so we can start multiple remote flooders in a single floodrpc request. In addition, the request param to request distributed flooding is removed.. the helm value should be sufficient

neocna/core: distributed flooding v0.3

---

.github/workflows/build-go.yaml
go.mod
go.sum

Bumping go.mod minimum supported version to v1.20 and moving build checks to v1.20 and v1.21
https://go.dev/doc/go1.21

Update: Bump golang build/support to v1.20 and v1.21

---

Makefile
cloudnetworkqueryfilter.go
doc/documentation.md
openapi3_autogen/cloudnetworkqueryfilter.json
specs/+cloudnetworkqueryfilter.spec

Adds a `notTags` attribute to `cloudnetworkqueryfilter` to store asset tags that should be selected against using the `not_in` operator in RQL.
Also excludes dot import checks with golangci-lint which have started to error out in the latest version.

[CNS-8149] support not_in filter for asset tags

---

identities_registry.go
specs/k8sresource.spec

adding prismaID+k8sID as the index for k8sresources in mongo. This got left out from the previous PR (https://github.com/PaloAltoNetworks/gaia/pull/967)

adding prismaID+k8sID as the index for k8sresources in mongo
